services:
- type: web
  name: xc
  env: docker
  region: frankfurt
  autoDeploy: false
  healthCheckPath: /dashboard
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: xc
      property: connectionString
  - key: PORT
    value: 8080
  - key: DB_QUERY_LIMIT_DEFAULT
    value: 50
databases:
- name: xc
  region: frankfurt
